### ISSUE TITLE
name 'config'is no defined.

### ISSUE THREAD

**Issue by sehwankim95** [princetonvisualai/overcoming-pretraining-bias#1]
When I execute main.py, I got a error message, name 'config'is no defined, at classifier.py 1042 line "config=config,"
Would you please correct this line?
please uploads the requirements with specific versions.... also, simple running example code.

Thank you in advance.

**Comment by Angelina-Wang** [comment]
Sorry about that! Added in the config, as well as sample running code

**Comment by sehwankim95** [comment]
Thank you for your quick and kind reply!
