### ISSUE TITLE
local variable 'model' referenced before assignment 

### ISSUE THREAD

**Issue by Aksh3141** [princetonvisualai/overcoming-pretraining-bias#3]
i am getting the following error upon running the code :-

File "classifier.py", line 872, in raytune
    model = get_model(args, out_features)
  File "classifier.py", line 537, in get_model
    model.to(device)
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by Angelina-Wang** [comment]
This is likely because the command line arg for model_type is not valid, I've just added in an assertion to catch this case.
